package values

const BRICK_DESTROYED_EVENT string = "BRICK_DESTROYED_EVENT"
const BALL_OUT_EVENT string = "BALL_OUT_EVENT"
const PADDLE_INCREASE_SIZE_EVENT string = "PADDLE_INCREASE_SIZE_EVENT"
const PADDLE_INCREASE_SPEED_EVENT string = "PADDLE_INCREASE_SPEED_EVENT"
const BALL_INCREASE_SPEED_EVENT string = "BALL_INCREASE_SPEED_EVENT"
const BALL_NEW_EVENT string = "BALL_NEW_EVENT"
const COLOR_GREEN_DOUBLE_POINTS_EVENT string = "COLOR_GREEN_DOUBLE_POINTS_EVENT"
const COLOR_YELLOW_DOUBLE_POINTS_EVENT string = "COLOR_YELLOW_DOUBLE_POINTS_EVENT"
const COLOR_ORANGE_DOUBLE_POINTS_EVENT string = "COLOR_ORANGE_DOUBLE_POINTS_EVENT"
const COLOR_RED_DOUBLE_POINTS_EVENT string = "COLOR_RED_DOUBLE_POINTS_EVENT"
const COLOR_ALL_DOUBLE_POINTS_EVENT string = "COLOR_ALL_DOUBLE_POINTS_EVENT"
const SHIELD_EVENT string = "SHIELD_EVENT"
